name: Apply Terraform

on:
  push:
    paths:
      - 'terraform-examples/*'
    branches:
      - main
      - guide/github-actions

jobs:
  tf-apply:
    name: Deploy Boards and Queries
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-examples
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Set Honeycomb API Key environment variable
        run: echo "HONEYCOMB_API_KEY=${{ secrets.BUILDEVENT_APIKEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color